--SQL Advance Case Study


--Q1--BEGIN 
SELECT DISTINCT State
FROM DIM_LOCATION
JOIN FACT_TRANSACTIONS ON DIM_LOCATION.IDLocation = FACT_TRANSACTIONS.IDLocation
JOIN DIM_DATE ON FACT_TRANSACTIONS.Date = DIM_DATE.DATE
WHERE DIM_DATE.YEAR >= 2005 ;

--Q1--END

--Q2--BEGIN
SELECT TOP 1 DIM_LOCATION.State	
FROM DIM_LOCATION
JOIN FACT_TRANSACTIONS ON DIM_LOCATION.IDLocation = FACT_TRANSACTIONS.IDLocation
JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDModel = DIM_MODEL.IDModel
JOIN DIM_MANUFACTURER ON DIM_MODEL.IDManufacturer = DIM_MANUFACTURER.IDManufacturer
WHERE DIM_MANUFACTURER.Manufacturer_Name = 'Samsung'
GROUP BY DIM_LOCATION.State
ORDER BY COUNT(*) DESC ;



--Q2--END

--Q3--BEGIN      
SELECT DIM_MODEL.Model_Name , DIM_LOCATION.ZipCode , DIM_LOCATION.State ,
COUNT(*) AS TRANSACTION_COUNT
FROM FACT_TRANSACTIONS
JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDModel = DIM_MODEL.IDModel
JOIN DIM_LOCATION ON FACT_TRANSACTIONS.IDLocation = DIM_LOCATION.IDLocation
GROUP BY DIM_MODEL.Model_Name , DIM_LOCATION.ZipCode , DIM_LOCATION.State ;





--Q3--END

--Q4--BEGIN
SELECT TOP 1 DIM_MODEL.Model_Name , DIM_MODEL.Unit_price
FROM DIM_MODEL
ORDER BY DIM_MODEL.Unit_price ;




--Q4--END

--Q5--BEGIN
SELECT DIM_MODEL.Model_Name , AVG( DIM_MODEL.Unit_price ) AS AVERAGE_PRICE
FROM DIM_MODEL
JOIN FACT_TRANSACTIONS ON DIM_MODEL.IDModel = FACT_TRANSACTIONS.IDModel
JOIN DIM_MANUFACTURER ON DIM_MODEL.IDManufacturer = DIM_MANUFACTURER.IDManufacturer
GROUP BY DIM_MODEL.Model_Name
ORDER BY AVG( FACT_TRANSACTIONS.Quantity ) DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY ;







--Q5--END

--Q6--BEGIN
SELECT DIM_CUSTOMER.Customer_Name , AVG(FACT_TRANSACTIONS.TotalPrice) AS AVERAGE_AMOUNT_SPENT
FROM DIM_CUSTOMER
JOIN FACT_TRANSACTIONS ON DIM_CUSTOMER.IDCustomer = FACT_TRANSACTIONS.IDCustomer
JOIN DIM_DATE ON FACT_TRANSACTIONS.Date = DIM_DATE.DATE
WHERE DIM_DATE.YEAR = 2009
GROUP BY DIM_CUSTOMER.Customer_Name
HAVING AVG(FACT_TRANSACTIONS.TotalPrice) > 500;




--Q6--END
	
--Q7--BEGIN  
SELECT DIM_MODEL.Model_Name	
FROM DIM_MODEL	
JOIN FACT_TRANSACTIONS ON DIM_MODEL.IDModel = FACT_TRANSACTIONS.IDModel
JOIN DIM_DATE ON FACT_TRANSACTIONS.Date = DIM_DATE.DATE
WHERE DIM_DATE.YEAR IN (2008,2009,2010)
GROUP BY DIM_MODEL.Model_Name
HAVING COUNT( DISTINCT ( DIM_DATE.YEAR)) = 3
ORDER BY SUM( FACT_TRANSACTIONS.Quantity) DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY ;









--Q7--END	
--Q8--BEGIN
SELECT DIM_MANUFACTURER.Manufacturer_Name , SUM(FACT_TRANSACTIONS.TotalPrice) AS TOTAL_SALES
FROM DIM_MANUFACTURER
JOIN DIM_MODEL ON DIM_MANUFACTURER.IDManufacturer = DIM_MODEL.IDManufacturer
JOIN FACT_TRANSACTIONS ON DIM_MODEL.IDModel = FACT_TRANSACTIONS.IDModel
JOIN DIM_DATE ON FACT_TRANSACTIONS.Date = DIM_DATE.DATE
WHERE DIM_DATE.YEAR IN (2009 , 2010)
GROUP BY DIM_MANUFACTURER.Manufacturer_Name
ORDER BY TOTAL_SALES DESC
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY ;










--Q8--END
--Q9--BEGIN
SELECT DISTINCT DIM_MANUFACTURER.Manufacturer_Name	
FROM DIM_MANUFACTURER
JOIN DIM_MODEL ON DIM_MANUFACTURER.IDManufacturer = DIM_MODEL.IDManufacturer
JOIN FACT_TRANSACTIONS ON DIM_MODEL.IDModel = FACT_TRANSACTIONS.IDModel
JOIN DIM_DATE ON FACT_TRANSACTIONS.Date = DIM_DATE.DATE
WHERE DIM_DATE.YEAR = 2010
AND DIM_MANUFACTURER.Manufacturer_Name NOT IN (
SELECT DISTINCT DIM_MANUFACTURER.Manufacturer_Name
FROM DIM_MANUFACTURER
JOIN DIM_MODEL ON DIM_MANUFACTURER.IDManufacturer = DIM_MODEL.IDManufacturer
JOIN FACT_TRANSACTIONS ON DIM_MODEL.IDModel = FACT_TRANSACTIONS.IDModel
JOIN DIM_DATE ON FACT_TRANSACTIONS.Date = DIM_DATE.DATE
WHERE DIM_DATE.YEAR = 2009) ;





--Q9--END

--Q10--BEGIN
SELECT TOP 100 CUSTOMERS , ORDER_YEAR , AVG_SPEND , AVG_QUANTITY,
LAG(AVG_SPEND) OVER (PARTITION BY CUSTOMERS ORDER BY ORDER_YEAR) AS PREV_AVG_SPEND,
((AVG_SPEND - LAG(AVG_SPEND) OVER (PARTITION BY CUSTOMERS ORDER BY ORDER_YEAR))/
LAG(AVG_SPEND) OVER (PARTITION BY CUSTOMERS ORDER BY ORDER_YEAR)) * 100 AS CHANGE_SPEND_PERCENTAGE
FROM ( SELECT DIM_CUSTOMER.Customer_Name AS CUSTOMERS , YEAR(FACT_TRANSACTIONS.DATE) AS ORDER_YEAR,
AVG(FACT_TRANSACTIONS.TotalPrice) AS AVG_SPEND , AVG(FACT_TRANSACTIONS.Quantity) AS AVG_QUANTITY
FROM DIM_CUSTOMER
JOIN FACT_TRANSACTIONS ON DIM_CUSTOMER.IDCustomer = FACT_TRANSACTIONS.IDCustomer
GROUP BY DIM_CUSTOMER.Customer_Name, YEAR( FACT_TRANSACTIONS.DATE)) AS CUSTOMER_YRARLY_STATS
ORDER BY AVG_SPEND DESC ;









--Q10--END
	